### ISSUE TITLE
GET Request '/api/properties' [staging env]

### ISSUE THREAD

**Issue by techturnip** [Lambda-School-Labs/property-manager-be#28]
Confirmed [IN APP] [INSOMNIA]:
Auth endpoints successfully POST and return a bearer token

Confirmed [IN APP] [INSOMNIA]:
GET Request w/ Auth to `/api/properties` returns 401 unauthorized using the token returned from Auth endpoints.

Used insomnia to test both bearer and header methods of sending token, same result.

Possible disconnect between Firebase and Node? 

Something is scuffed between Token generation and validation on the staging deployment. Didn't see any glaring issues in the code, considering I don't think any of the Auth logic regarding properties or login/register have been messed with since previous deployment.

**Comment by hagnerd** [comment]
Hey just saw this 😅. This is resolved.
