### ISSUE TITLE
/get basic user info

### ISSUE THREAD

**Issue by IXLives** [Lambda-School-Labs/property-manager-be#31]
Would like to be able to make a /get request to a user endpoint for basic info about the user like their firstName, lastName and the type of user they are

**Comment by hagnerd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Endpoint to return basic user info](https://trello.com/c/vZKAN1dX/85-implement-endpoint-to-return-basic-user-info)
