### ISSUE TITLE
CRUD for work orders

### ISSUE THREAD

**Issue by IXLives** [Lambda-School-Labs/property-manager-be#59]
need an endpoint to hit to add, get, edit and delete work orders 🗡

**Comment by hagnerd** [comment]
Create, get and get all are working currently on staging, update and delete will be ready shortly.

**Comment by KAfable** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Master Branch](https://trello.com/c/wouRrBKt/30-add-master-branch)

**Comment by nickdurbin** [comment]
Added CRUD on last release.
