### ISSUE TITLE
Add user info to auth response

### ISSUE THREAD

**Issue by IXLives** [Lambda-School-Labs/property-manager-be#60]
We need to receive user type along with the token on the front-end for conditional display of the dashboard based on user type. Thanks back end friends

**Comment by hagnerd** [comment]
@IXLives Do you also want first/last name and email?

**Comment by IXLives** [comment]
just email and type since no one will have a firstname, lastname on creation

**Comment by hagnerd** [comment]
#61 Addresses this and once merged this issue can be closed

**Comment by hagnerd** [comment]
Resolved with #61 which has been merged
