### ISSUE TITLE
Set up express.json() middleware

### ISSUE THREAD

**Issue by hagnerd** [Lambda-School-Labs/property-manager-be#8]
Add the ability to parse JSON data from req.body using express.json() global middleware

**Comment by hagnerd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up express.json() as global middleware](https://trello.com/c/RmXB8wKA/41-set-up-expressjson-as-global-middleware)

**Comment by sandyjernigan** [comment]
Looks good.
